### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by jpcartailler** [milescsmith/s2a#1]
Greetings,

Thanks for putting this together. 
I followed the installation from https://rdrr.io/github/milescsmith/s2a/:
```
install.packages("remotes")
remotes::install_github("milescsmith/s2a")
```

However, when I try to load the library, I get an error:

```
> library(s2a)
Error: package or namespace load failed for ‘s2a’:
 .onLoad failed in loadNamespace() for 's2a', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 's2a'
> 
```

Is there a python module to also install?

Thanks!
JP

**Comment by milescsmith** [comment]
Yes, there's Python components to interface with scanpy.  You should be able to install them with:
```
pip install git+https://github.com/milescsmith/s2a
```
